# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/yasi',
                'doc_host': 'https://Jack-Byte.github.io',
                'git_url': 'https://github.com/Jack-Byte/yasi',
                'lib_path': 'yasi'},
  'syms': {'yasi.core': {'yasi.core.foo': ('core.html#foo', 'yasi/core.py')}}}
